import { createWildcardForAssignmentPatternOrDefaultParamValuesNodesComparator } from '/parserSettings/nodeComparatorFactories/JavaScriptSpecific/wildcardForAssignmentPatternOrDefaultParamValues'

export const wildcardForAssignmentPatternOrDefaultParamValuesNodesComparator =
  createWildcardForAssignmentPatternOrDefaultParamValuesNodesComparator()
