import { createWildcardForAssignmentPatternOrDefaultParamValuesNodesComparator } from '../../nodeComparatorFactories/JavaScriptSpecific/wildcardForAssignmentPatternOrDefaultParamValues'

export const wildcardForAssignmentPatternOrDefaultParamValuesNodesComparator =
  createWildcardForAssignmentPatternOrDefaultParamValuesNodesComparator()
