import { createFurtherProcessingOfTypeWildcardsInIdentifiersNodesComparator } from '../../nodeComparatorFactories/TypeScriptSpecific/furtherProcessingOfTypeWildcardsInIdentifiers'

export const furtherProcessingOfTypeWildcardsInIdentifiersNodesComparator =
  createFurtherProcessingOfTypeWildcardsInIdentifiersNodesComparator()
