import { createMatchObjectPropertiesOfDifferentTypesNodesComparator } from '../../nodeComparatorFactories/JavaScriptSpecific/matchObjectPropertiesOfDifferentTypes'

export const matchObjectPropertiesOfDifferentTypesNodesComparator =
  createMatchObjectPropertiesOfDifferentTypesNodesComparator()
